language: java
dist: trusty
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - rm -rf $HOME/.m2/repository
  - mvn clean package -B -V

after_success:
  - sh set_tags.sh

env:
  global:
    secure: be813b27eb0a1420f6e88915c2625295715fa376

#deploy:
#  provider: releases
#  api_key:
#    secure: be813b27eb0a1420f6e88915c2625295715fa376
#  file: "target/Console-*.zip"
#  file_glob: "true"
#  skip_cleanup: true
#  on:
#    branch: master
#    repo: taljmars/DroneGCS

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: true
