package com.dronegcs.console.services.internal;

import com.dronedb.persistence.scheme.Mission;
import com.dronedb.persistence.scheme.MissionItem;
import com.dronegcs.console.services.MissionCompilerSvc;
import com.dronegcs.console.services.internal.convertors.DatabaseToMavlinkItemConvertor;
import com.dronegcs.console.services.internal.convertors.MavlinkItemToDatabaseConvertor;
import com.dronegcs.mavlink.is.drone.Drone;
import com.dronegcs.mavlink.is.drone.mission.DroneMission;
import com.dronegcs.mavlink.is.drone.mission.DroneMissionItem;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import javax.validation.constraints.NotNull;
import java.util.Iterator;
import java.util.List;

/**
 * Created by taljmars on 3/18/17.
 */
@Component
public class MissionCompilerSvcImpl implements MissionCompilerSvc
{
    @Autowired @NotNull(message = "Internal Error: Failed to get drone")
    private Drone drone;

    @PostConstruct
    private void init() {
        System.err.println("Mission Compiler started");
    }


    @Override
    public DroneMission compile(Mission mission) {

        DroneMission droneMission = new DroneMission();
        droneMission.setDrone(drone);

        droneMission.setDefaultAlt(mission.getDefaultAlt());

        DatabaseToMavlinkItemConvertor databaseToMavlinkItemConvertor = new DatabaseToMavlinkItemConvertor();
        databaseToMavlinkItemConvertor.setDroneMission(droneMission);

        Iterator<MissionItem> itr = mission.getMissionItems().iterator();
        while (itr.hasNext())
            itr.next().accept(databaseToMavlinkItemConvertor);

        return databaseToMavlinkItemConvertor.getDroneMission();
    }

    @Override
    public Mission decompile(DroneMission droneMission) {
        Mission mission = new Mission();
        mission.setDefaultAlt(droneMission.getDefaultAlt());
        mission.setName("AutoGenerated_Name_" + System.currentTimeMillis());
        List<DroneMissionItem> droneMissionItemList = droneMission.getItems();

        MavlinkItemToDatabaseConvertor mavlinkItemToDatabaseConvertor = new MavlinkItemToDatabaseConvertor();
        mavlinkItemToDatabaseConvertor.setMission(mission);

        Iterator<DroneMissionItem> itr = droneMissionItemList.iterator();
        while (itr.hasNext()) {
            DroneMissionItem droneMissionItem = itr.next();
            droneMissionItem.accept(mavlinkItemToDatabaseConvertor);
        }

        return mavlinkItemToDatabaseConvertor.getMission();
    }
}
